- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
  tasks:
    - name: Gather tags 
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: list
        resource: "{{ INSTANCE_ID }}"
      register: tags
   
    - name: Display tags
      debug:
        var: tags.tags
 
    - name: Add tags to resrouce 
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        resource: snap-0e5eac3eff7e7bb6d
        tags: 
          Name: pepe
          system: erp
          version: 1.2
        state: present
