- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
  tasks:
    - name: Change instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags: 
          Name: test
