- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
  tasks:
    - name: Create new Security Group
      ec2_group:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: test 
        description: EC2 test Security Group
        vpc_id: "{{ VPC_ID }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: create a new ec2 keypair
      ec2_key: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: ec2key 
      register: keypair

    - debug:
        var: keypair

    - name: write new private key to file locally
      lineinfile: 
        create: yes
        path: /etc/ansible_aws/aws_keys/ec2key.pem
        line: "{{ keypair.key.private_key }}"
        mode: 0600

    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        instance_type: t2.micro
        key_name: ec2key
        image: ami-09d95fab7fff3776c #Amazon Linux 2 AMI 
        assign_public_ip: yes
        vpc_subnet_id: "{{ SUBNET }}" #Subnet dentro de VPC que ya existe
        group: test #Security Group que ya existe 
        wait: true
        exact_count: 1
        count_tag:
          Name: test
        instance_tags: 
          Name: test
      register: ec2
    - debug:
        var: ec2

    - name: add host to inventory
      add_host:
        hostname: '{{ item.public_ip }}'
        groupname: demogroup #el nombre de grupo que pondremos en el inventario
        #anadimos variables
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no" 
        ansible_ssh_private_key_file: aws_keys/ec2key.pem #clave privada que usaremos para conectar al servidor
      loop: '{{ ec2.instances }}'

#validamos conectividad con las instancias creadas que pertenecen al grupo demogroup
- hosts: demogroup
  gather_facts: no
  remote_user: ec2-user
  tasks:
    - name: wait for SSH
      wait_for_connection: 
        delay: 5
        timeout: 90

    - name: Check host status
      ping:
