- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
  tasks:
    #Con este play creo una imagen a partir de una instancia ec2
    - name: Create new AMI
      ec2_ami:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-08eb48a5538c1e51b #Instance ID del ec2
        name: MyNewAMI
        #wait: yes
        state: present
