- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
  tasks:
    - name: remove old key 
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: ec2key
        state: absent
  
    - name: create a new ec2 keypair
      ec2_key: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: ec2key 
      register: keypair

    - debug:
        var: keypair

    - name: write new private key to file locally
      lineinfile: 
        create: yes
        path: /etc/ansible_aws/aws_keys/ec2key.pem
        line: "{{ keypair.key.private_key }}"
        mode: 0600
