- hosts: localhost
  gather_facts: no
  vars_files:
    - ../aws_keys/keys.yml
    - ../aws_keys/general_vars.yml
  tasks:
    - name: Create new EBS Volume and Attach to "{{ NAME }}_rhel8"
      ec2_vol:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        zone: "{{ ec2_rhel8_zone }}" 
        volume_size: "10" #en GB
        name: "{{ NAME }}_rhel8" 
        instance: "{{ ec2_rhel8_id }}"
        device_name: "{{ device_name }}" 
        delete_on_termination: yes
      register: vol_info_rhel8

    - debug:
        var: vol_info_rhel8
      tags: create 

    - name: Create new EBS Volume to "{{ NAME }}_sles15"
      ec2_vol:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        zone: "{{ ec2_sles15_zone }}"
        volume_size: "10" #en GB
        name: "{{ NAME }}_sles15" 
        instance: "{{ ec2_sles15_id }}"
        device_name: "{{ device_name }}"
        delete_on_termination: yes
      register: vol_info_sles15
 
    - debug:
        var: vol_info_sles15
      tags: create 
